// 各步骤表单配置：定义字段、类型、占位符
export interface FormField {
  key: string;
  label: string;
  type?: 'text' | 'textarea' | 'date' | 'select';
  placeholder?: string;
  rows?: number;
  fullSpan?: boolean;  // 是否占满两列
  auditTypes?: string[];  // 适用的审计类型（留空表示通用）
}

/** 谈话记录子页签配置 */
export interface InterviewTabConfig {
  key: string;              // Tab 标识
  label: string;            // Tab 显示名称
  template?: string;        // 导出模板名
  exportFile: string;       // 导出文件名
  fields: FormField[];      // 表单字段
  autoFillFromProject?: Record<string, string>;
  defaultValues?: Record<string, string>;
  /** 自动从前序步骤导入同名字段 */
  importFrom?: string[];
}

export interface StageFormConfig {
  title: string;           // 表单标题
  template?: string;        // 导出模板名（对应 resources/templates/ 中的文件名，不含扩展名）
  exportFile: string;      // 导出文件名
  fields: FormField[];
  autoFillFromProject?: Record<string, string>;  // 从项目信息自动填充：formKey -> projectKey
  defaultValues?: Record<string, string>;  // 表单字段默认值（通常来自模板内容）
  /** 多页签配置（如 interview_record） */
  tabs?: InterviewTabConfig[];
}

export const STAGE_FORM_CONFIGS: Record<string, StageFormConfig> = {
  notice: {
    title: '审计通知书',
    // template 根据审计类型动态设置（见 GenericStageForm.vue）
    exportFile: '审计通知书.docx',
    autoFillFromProject: { auditedUnit: 'auditedTarget', auditProject: 'name' },
    defaultValues: {
      auditCommitteeOffice: '中共科右前旗审计委员会办公室',
      auditOrg: '科右前旗审计局',
      content: `审计"八不准"工作纪律`,
    },
    fields: [
      { key: 'auditCommitteeOffice', label: '审计委员会办公室', fullSpan: true, placeholder: '例：中共科右前旗委审计委员会办公室', auditTypes: ['经济责任审计'] },
      { key: 'auditOrg', label: '审计机关全称', fullSpan: true, placeholder: '例：科右前旗审计局' },
      { key: 'documentNumber', label: '文号', placeholder: '例：审（委）办经责通〔2024〕1号'},
      { key: 'auditedUnit', label: '被审计单位', fullSpan: true, placeholder: '例：科右前旗财政局' },
      { key: 'auditedLeaderName', label: '被审计领导干部姓名', auditTypes: ['经济责任审计'] },
      { key: 'auditedLeaderPosition', label: '被审计领导干部职务', auditTypes: ['经济责任审计'] },
      { key: 'auditStartDate', label: '审计开始日期', type: 'date' },
      { key: 'auditYear', label: '审计年度', placeholder: '例：2024', auditTypes: ['预算执行审计'] },
      { key: 'auditProject', label: '审计项目名称', fullSpan: true, auditTypes: ['专项审计调查'] },
      { key: 'teamLeader', label: '审计组组长' },
      { key: 'teamDeputyLeader', label: '副组长' },
      { key: 'teamMembers', label: '审计组成员（逗号分隔）', fullSpan: true, placeholder: '请输入成员姓名，用逗号分隔' },
      { key: 'text', label: '配合联系人/财务负责人', fullSpan: true, placeholder: '例：单位财务负责人或联络人姓名', auditTypes: ['经济责任审计'] },
      { key: 'ccUnit', label: '抄送单位' },
      { key: 'issuingOrg', label: '印发机关', fullSpan: true, placeholder: '例：科右前旗审计局' },
      { key: 'issueDate', label: '印发日期', type: 'date' },
      { key: 'content', label: '附件', type: 'textarea', rows: 4, fullSpan: true, placeholder: '通知书附件内容，留空则不显示' },
    ],
  },
  eight_prohibitions: {
    title: '通知附件八不准',
    template: '04通知附件八不准',
    exportFile: '通知附件八不准.docx',
    fields: [],
  },
  delivery_receipt: {
    title: '审计文书送达回证',
    template: '06审计文书送达回证',
    exportFile: '审计文书送达回证.docx',
    autoFillFromProject: { projectName: 'name', recipientUnit: 'auditedTarget' },
    fields: [
      { key: 'documentName', label: '文书名称', placeholder: '例：审计通知书' },
      { key: 'documentNo', label: '文书编号' },
      { key: 'recipientUnit', label: '收件单位' },
      { key: 'deliveryMethod', label: '送达方式' },
      { key: 'deliveryDate', label: '送达日期', type: 'date' },
      { key: 'address', label: '送达地址', fullSpan: true },
      { key: 'postCode', label: '邮编' },
      { key: 'content', label: '备注内容', type: 'textarea', rows: 6, fullSpan: true },
    ],
  },
  audit_announcement: {
    title: '经济责任审计公示',
    template: '05经济责任审计公示',
    exportFile: '经济责任审计公示.docx',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '审计项目名称', fullSpan: true },
      { key: 'auditedLeaderName', label: '被审计领导干部姓名' },
      { key: 'auditedLeaderPosition', label: '被审计领导干部职务' },
      { key: 'auditStartDate', label: '审计开始日期', type: 'date' },
      { key: 'auditPeriod', label: '审计期间', placeholder: '例：2023年1月至2024年12月' },
      { key: 'announcementStartDate', label: '公示开始日期', type: 'date' },
      { key: 'announcementEndDate', label: '公示结束日期', type: 'date' },
      { key: 'contactPhone', label: '联系电话' },
      { key: 'contactAddress', label: '联系地址', fullSpan: true },
      { key: 'content', label: '公示内容', type: 'textarea', rows: 6, fullSpan: true },
      { key: 'text', label: '补充文本' },
    ],
  },
  commitment_letter: {
    title: '被审计单位承诺书',
    template: '07被审计单位承诺书',
    exportFile: '被审计单位承诺书.docx',
    fields: [],
  },
  survey: {
    title: '被审计单位基本情况表',
    template: '08调查了解记录基本情况表',
    exportFile: '被审计单位基本情况表.xlsx',
    autoFillFromProject: { unitName: 'auditedTarget' },
    fields: [
      { key: 'unitName', label: '单位名称' },
      { key: 'unitNature', label: '单位性质' },
      { key: 'legalRepresentative', label: '法人代表' },
      { key: 'supervisingUnit', label: '主管单位' },
      { key: 'staffQuota', label: '人员编制' },
      { key: 'currentStaffCount', label: '期末人数' },
      { key: 'orgStructure', label: '机构设置情况', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'responsibilityScope', label: '职责范围/经营范围', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'lawExecution', label: '相关法律法规、政策及其执行情况', type: 'textarea', rows: 4, fullSpan: true },
      { key: 'financialSystem', label: '财政财务管理体制和业务管理体制', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'performanceIndicators', label: '适用的业绩指标体系', type: 'textarea', rows: 2, fullSpan: true },
      { key: 'internalControl', label: '相关内部控制及其执行情况', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'infoSystems', label: '相关信息系统及其电子数据情况', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'economicEnvironment', label: '经济环境、行业状况及其他外部因素', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'previousAudit', label: '以往接受审计情况', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'otherInfo', label: '其他需要了解的情况', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'fillerName', label: '填表人' },
      { key: 'fillDate', label: '填报日期', type: 'date' },
    ],
  },
  survey_assessment: {
    title: '评估被审计单位存在重要问题的可能性',
    template: '09评估被审计单位存在问题可能性',
    exportFile: '评估被审计单位存在重要问题的可能性.docx',
    fields: [],
  },
  survey_measures: {
    title: '确定审计事项和审计应对措施',
    template: '10确定审计事项和审计应对措施',
    exportFile: '确定审计事项和审计应对措施.docx',
    fields: [],
  },
  plan: {
    title: '审计实施方案',
    template: '11审计实施方案',
    exportFile: '审计实施方案.docx',
    autoFillFromProject: { projectName: 'name', auditedUnit: 'auditedTarget' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'auditedUnit', label: '被审计单位全称', fullSpan: true },
      { key: 'teamLeader', label: '组长' },
      { key: 'startDate', label: '开始日期', type: 'date' },
      { key: 'teamMembers', label: '审计组成员及分工', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'auditScope', label: '审计范围', type: 'textarea', rows: 2, fullSpan: true },
      { key: 'auditFocus', label: '审计重点', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'auditMethod', label: '审计方法', type: 'textarea', rows: 2, fullSpan: true },
      { key: 'schedule', label: '时间安排', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'endDate', label: '结束日期', type: 'date' },
    ],
  },
  task_list: {
    title: '任务清单',
    exportFile: '任务清单.xls',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'taskListContent', label: '任务清单内容', type: 'textarea', rows: 8, fullSpan: true, placeholder: '审计任务分解、责任人、完成时限等' },
      { key: 'compileDate', label: '编制日期', type: 'date' },
    ],
  },
  interview_record: {
    title: '谈话记录',
    exportFile: '谈话记录.docx',
    fields: [], // 使用 tabs，不使用顶层 fields
    tabs: [
      {
        key: 'interview_transcript',
        label: '调查谈话笔录',
        template: '13调查谈话笔录模板',
        exportFile: '调查谈话笔录.docx',
        importFrom: ['notice'],
        autoFillFromProject: { projectName: 'name' },
        fields: [
          { key: 'projectName', label: '项目名称', fullSpan: true },
          { key: 'auditOrg', label: '审计机关全称', fullSpan: true, placeholder: '例：科右前旗审计局' },
          { key: 'interviewLocation', label: '谈话地点' },
          { key: 'interviewTime', label: '谈话时间' },
          { key: 'interviewer', label: '谈话人' },
          { key: 'recorder', label: '记录人' },
          { key: 'intervieweeName', label: '被谈话人姓名' },
          { key: 'intervieweeIdNumber', label: '身份证号' },
          { key: 'intervieweeGender', label: '性别' },
          { key: 'intervieweePolitical', label: '政治面貌' },
          { key: 'intervieweeEducation', label: '文化程度' },
          { key: 'intervieweeEthnicity', label: '民族' },
          { key: 'intervieweeContact', label: '联系方式' },
          { key: 'intervieweeUnit', label: '工作单位' },
          { key: 'intervieweePosition', label: '职务' },
          { key: 'auditMatter', label: '调查事项', fullSpan: true, placeholder: '根据《审计法》第三十七条，现就**事项进行调查核实' },
          { key: 'questionContent', label: '问', type: 'textarea', rows: 6, fullSpan: true },
          { key: 'answerContent', label: '答', type: 'textarea', rows: 6, fullSpan: true },
          { key: 'signatureConfirm', label: '被谈话人签名确认', placeholder: '以上笔录我看过，和我说的相符' },
        ],
      },
      {
        key: 'work_report_outline',
        label: '述职报告提纲',
        template: '15述职报告提纲',
        exportFile: '述职报告提纲.docx',
        importFrom: ['notice'],
        autoFillFromProject: { reporterName: 'auditedLeaderName' },
        fields: [
          { key: 'reporterName', label: '述职人姓名', placeholder: '自动从通知书引用被审计领导干部姓名' },
          { key: 'tenureStartYear', label: '任职起始年' },
          { key: 'tenureStartMonth', label: '任职起始月' },
          { key: 'tenureEndYear', label: '任职截止年' },
          { key: 'tenureEndMonth', label: '任职截止月' },
          { key: 'unitName', label: '单位' },
          { key: 'positionTitle', label: '职务称谓', placeholder: '例：局长' },
          { key: 'divisionOfLabor', label: '一、本人在单位内的分工情况', type: 'textarea', rows: 2, fullSpan: true },
          { key: 'budgetExecution', label: '二、任期内预算执行情况（近3年）', type: 'textarea', rows: 3, fullSpan: true },
          { key: 'financialStatus', label: '三、任期内财政收支和财务收支情况', type: 'textarea', rows: 4, fullSpan: true },
          { key: 'institutionalRules', label: '四、任期内建立的规章制度及执行情况', type: 'textarea', rows: 4, fullSpan: true },
          { key: 'authenticityLegality', label: '五、预算执行和财务收支真实合法效益情况', type: 'textarea', rows: 3, fullSpan: true },
          { key: 'socialOrganizations', label: '六、本单位管理的社会团体财务状况', type: 'textarea', rows: 2, fullSpan: true },
          { key: 'majorInvestments', label: '七、任期内重要投资项目建设管理情况', type: 'textarea', rows: 2, fullSpan: true },
          { key: 'unfinishedProjects', label: '八、未了工程及经济往来事项', type: 'textarea', rows: 3, fullSpan: true },
          { key: 'subordinateSupervision', label: '九、对下属单位监督管理情况', type: 'textarea', rows: 2, fullSpan: true },
          { key: 'publicPropertySettlement', label: '十、个人保管公物公款及往来结清情况', type: 'textarea', rows: 2, fullSpan: true },
          { key: 'majorDecisions', label: '十一、任期内重大决策及效益', type: 'textarea', rows: 3, fullSpan: true },
          { key: 'economicAchievements', label: '十二、经济管理中取得的业绩', type: 'textarea', rows: 2, fullSpan: true },
          { key: 'personalEconomic', label: '十三、个人经济行为（财经纪律、报销等）', type: 'textarea', rows: 4, fullSpan: true },
          { key: 'otherViolations', label: '十四、其他违反廉洁从政规定问题', type: 'textarea', rows: 2, fullSpan: true },
          { key: 'lawCompliance', label: '十五、遵守经济法律法规情况', type: 'textarea', rows: 2, fullSpan: true },
          { key: 'selfEvaluation', label: '十六、经济责任方面简要自我评价', type: 'textarea', rows: 3, fullSpan: true },
          { key: 'achievementsAndShortcomings', label: '十七、任职期间主要成绩和不足', type: 'textarea', rows: 3, fullSpan: true },
          { key: 'reporterSignature', label: '述职人签字', placeholder: '述职人签字' },
          { key: 'reportDate', label: '报告日期', type: 'date' },
        ],
      },
      {
        key: 'assessment_county',
        label: '民主测评(旗直)',
        template: '17民主测评表旗直领导干部',
        exportFile: '民主测评表(旗直).docx',
        importFrom: ['notice'],
        // 纯导出：占位符自动从通知书引用，无需用户输入
        fields: [],
      },
      {
        key: 'assessment_township',
        label: '民主测评(乡镇)',
        template: '18民主测评表乡镇政府领导干部',
        exportFile: '民主测评表(乡镇).docx',
        importFrom: ['notice'],
        // 纯导出：占位符自动从通知书引用，无需用户输入
        fields: [],
      },
    ],
  },
  evidence: {
    title: '审计取证单',
    template: '14审计取证单',
    exportFile: '审计取证单.docx',
    autoFillFromProject: { projectName: 'name', auditedUnit: 'auditedTarget' },
    fields: [
      { key: 'serialNumber', label: '编号' },
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'auditedUnit', label: '被审计（调查）单位' },
      { key: 'matterSummary', label: '审计（调查）事项摘要', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'evidenceContent', label: '证据内容', type: 'textarea', rows: 5, fullSpan: true },
      { key: 'legalBasis', label: '法律法规依据', type: 'textarea', rows: 2, fullSpan: true },
      { key: 'auditorName', label: '审计人员' },
      { key: 'compileDate', label: '编制日期', type: 'date' },
      { key: 'providerOpinion', label: '证据提供单位意见', type: 'textarea', rows: 2, fullSpan: true },
      { key: 'providerSignature', label: '证据提供单位盖章/签名' },
      { key: 'feedbackDeadline', label: '反馈截止日期', type: 'date' },
    ],
  },
  working_paper: {
    title: '审计工作底稿',
    template: '16审计工作底稿',
    exportFile: '审计工作底稿.docx',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'indexNumber', label: '索引号' },
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'auditMatter', label: '审计（调查）事项' },
      { key: 'auditorName', label: '审计人员' },
      { key: 'compileDate', label: '编制日期', type: 'date' },
      { key: 'auditProcess', label: '审计过程（步骤、方法、证据）', type: 'textarea', rows: 5, fullSpan: true },
      { key: 'factSummary', label: '审计认定的事实摘要', type: 'textarea', rows: 5, fullSpan: true },
      { key: 'auditConclusion', label: '审计结论', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'reviewerOpinion', label: '审核意见', type: 'textarea', rows: 2, fullSpan: true },
      { key: 'reviewerName', label: '审核人员' },
      { key: 'reviewDate', label: '审核日期', type: 'date' },
      { key: 'attachmentCount', label: '附件页数' },
      { key: 'val', label: '引用底稿/证据编号' },
    ],
  },
  working_paper_summary: {
    title: '审计底稿汇总表',
    exportFile: '审计底稿汇总表.xls',
    fields: [],
  },
  task_list_completion: {
    title: '任务清单完成情况',
    template: '19任务清单完成情况',
    exportFile: '任务清单完成情况.xls',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'completionContent', label: '任务完成情况', type: 'textarea', rows: 10, fullSpan: true, placeholder: '各任务完成情况、责任人完成时限等' },
      { key: 'compileDate', label: '填报日期', type: 'date' },
    ],
  },
  report: {
    title: '审计组审计报告',
    exportFile: '审计组审计报告.docx',
    autoFillFromProject: { auditedUnit: 'auditedTarget', auditProject: 'name' },
    fields: [
      { key: 'documentNumber', label: '文号', placeholder: '例：*审（委）办经责报〔20**〕**号' },
      { key: 'auditedUnit', label: '被审计单位' },
      { key: 'auditedLeaderName', label: '被审计领导干部' },
      { key: 'auditProject', label: '审计项目' },
      { key: 'auditStartDate', label: '审计开始日期', type: 'date' },
      { key: 'auditEndDate', label: '审计结束日期', type: 'date' },
      { key: 'leaderPosition1', label: '被审计领导职务（一）' },
      { key: 'leaderPosition2', label: '被审计领导职务（二）' },
      { key: 'basicInfo', label: '被审计单位基本情况', type: 'textarea', rows: 6, fullSpan: true, placeholder: '简要表述被审计单位的背景信息、性质、组织结构等' },
      { key: 'mainWork', label: '履行经济责任所做的主要工作', type: 'textarea', rows: 6, fullSpan: true },
      { key: 'overallEvaluation', label: '总体评价', type: 'textarea', rows: 4, fullSpan: true },
      { key: 'problemsFound', label: '审计发现的主要问题', type: 'textarea', rows: 8, fullSpan: true },
      { key: 'responsibility', label: '责任认定', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'auditSuggestions', label: '审计建议', type: 'textarea', rows: 4, fullSpan: true },
      { key: 'text', label: '审计期间', type: 'textarea', rows: 3, fullSpan: true, placeholder: '审计期间、范围、重点等文本内容' },
      { key: 'content', label: '报告正文内容', type: 'textarea', rows: 10, fullSpan: true, placeholder: '报告正文详细内容' },
      { key: 'shortText', label: '补充说明', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'name', label: '相关人员姓名' },
      { key: 'val', label: '其他数值' },
    ],
  },
  report_consultation: {
    title: '审计报告征求意见书',
    template: '21审计报告征求意见书',
    exportFile: '审计报告征求意见书.docx',
    autoFillFromProject: { auditedUnit: 'auditedTarget', projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'auditedUnit', label: '被审计单位' },
      { key: 'consultationContent', label: '征求意见内容', type: 'textarea', rows: 8, fullSpan: true, placeholder: '审计报告摘要及征求意见事项' },
      { key: 'feedbackDeadline', label: '反馈截止日期', type: 'date' },
      { key: 'contactPerson', label: '联系人' },
      { key: 'contactPhone', label: '联系电话' },
      { key: 'issueDate', label: '发出日期', type: 'date' },
      { key: 'content', label: '正文内容', type: 'textarea', rows: 6, fullSpan: true },
      { key: 'text', label: '描述文本', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'val', label: '编号/日期值' },
    ],
  },
  audit_opinion: {
    title: '审核意见书',
    template: '22审核意见书',
    exportFile: '审核意见书.docx',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'reviewerName', label: '审核人' },
      { key: 'reviewDate', label: '审核日期', type: 'date' },
      { key: 'reviewOpinion', label: '审核意见', type: 'textarea', rows: 6, fullSpan: true, placeholder: '对审计报告的审核意见' },
    ],
  },
  review_opinion: {
    title: '复核意见书',
    template: '23复核意见书',
    exportFile: '复核意见书.docx',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'reviewerName', label: '复核人' },
      { key: 'reviewDate', label: '复核日期', type: 'date' },
      { key: 'reviewOpinion', label: '复核意见', type: 'textarea', rows: 6, fullSpan: true, placeholder: '对审计报告的复核意见' },
    ],
  },
  adjudication_opinion: {
    title: '审理意见书',
    template: '24审理意见书',
    exportFile: '审理意见书.docx',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'adjudicatorName', label: '审理人' },
      { key: 'adjudicationDate', label: '审理日期', type: 'date' },
      { key: 'adjudicationOpinion', label: '审理意见', type: 'textarea', rows: 6, fullSpan: true, placeholder: '对审计报告的审理意见' },
    ],
  },
  adjudication_meeting: {
    title: '审理会议纪要',
    template: '26审理会议纪要',
    exportFile: '审理会议纪要.docx',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'meetingDate', label: '会议日期', type: 'date' },
      { key: 'meetingLocation', label: '会议地点' },
      { key: 'attendees', label: '参会人员', fullSpan: true },
      { key: 'meetingContent', label: '会议内容', type: 'textarea', rows: 8, fullSpan: true, placeholder: '审理会讨论内容及决议' },
      { key: 'meetingConclusion', label: '会议结论', type: 'textarea', rows: 4, fullSpan: true },
      { key: 'recorderName', label: '记录人' },
    ],
  },
  draft_cover: {
    title: '代拟稿封皮',
    template: '25代拟稿封皮',
    exportFile: '代拟稿封皮.docx',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'reportTitle', label: '报告标题', fullSpan: true },
      { key: 'authorName', label: '拟稿人' },
      { key: 'reviewerName', label: '审核人' },
      { key: 'draftDate', label: '拟稿日期', type: 'date' },
      { key: 'version', label: '版本号' },
      { key: 'remarks', label: '备注', type: 'textarea', rows: 3, fullSpan: true },
    ],
  },
  external_report: {
    title: '对外报告',
    template: '27预算执行对外报告',
    exportFile: '对外报告.docx',
    autoFillFromProject: { projectName: 'name', auditedUnit: 'auditedTarget' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'auditedUnit', label: '被审计单位' },
      { key: 'reportNumber', label: '报告编号' },
      { key: 'reportDate', label: '报告日期', type: 'date' },
      { key: 'reportContent', label: '报告内容', type: 'textarea', rows: 12, fullSpan: true, placeholder: '对外发布的完整报告内容' },
      { key: 'issueOrg', label: '发文机关' },
      { key: 'issuerSignature', label: '签发人签名' },
      { key: 'content', label: '正文内容', type: 'textarea', rows: 8, fullSpan: true },
      { key: 'text', label: '描述文本', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'name', label: '人员姓名' },
      { key: 'val', label: '编号/数值' },
    ],
  },
  audit_decision: {
    title: '审计决定书',
    exportFile: '审计决定书.docx',
    autoFillFromProject: { auditedUnit: 'auditedTarget' },
    fields: [
      { key: 'documentNumber', label: '文号' },
      { key: 'auditedUnit', label: '被审计单位' },
      { key: 'decisionContent', label: '审计决定内容', type: 'textarea', rows: 10, fullSpan: true, placeholder: '审计处理决定内容' },
      { key: 'decisionDate', label: '决定日期', type: 'date' },
      { key: 'issueOrg', label: '发文机关' },
      { key: 'content', label: '正文内容', type: 'textarea', rows: 8, fullSpan: true },
      { key: 'text', label: '描述文本', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'name', label: '人员姓名' },
      { key: 'val', label: '编号/数值' },
    ],
  },
  result_report: {
    title: '经责审计结果报告',
    exportFile: '经责审计结果报告.docx',
    autoFillFromProject: { projectName: 'name', auditedLeaderName: 'auditedTarget' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'auditedLeaderName', label: '被审计领导干部' },
      { key: 'auditedLeaderPosition', label: '被审计领导职务' },
      { key: 'reportContent', label: '结果报告内容', type: 'textarea', rows: 12, fullSpan: true, placeholder: '经济责任审计结果报告完整内容' },
      { key: 'reportDate', label: '报告日期', type: 'date' },
      { key: 'content', label: '正文内容', type: 'textarea', rows: 8, fullSpan: true, placeholder: '报告正文详细内容' },
      { key: 'text', label: '期间/描述文本', type: 'textarea', rows: 3, fullSpan: true },
      { key: 'name', label: '人员姓名' },
      { key: 'val', label: '编号/数值' },
    ],
  },
  issues_not_reflected: {
    title: '未在报告中反映问题清单',
    exportFile: '未在报告中反映问题清单.docx',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'issuesContent', label: '未在报告中反映的问题清单', type: 'textarea', rows: 10, fullSpan: true, placeholder: '逐条列出未在审计报告中反映的问题及原因' },
      { key: 'compileDate', label: '填报日期', type: 'date' },
    ],
  },
  issue_ledger: {
    title: '审计问题台账',
    exportFile: '审计问题台账.xls',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'ledgerContent', label: '问题台账内容', type: 'textarea', rows: 12, fullSpan: true, placeholder: '逐条登记审计发现的问题、整改情况、责任人员等' },
      { key: 'compileDate', label: '填报日期', type: 'date' },
    ],
  },
  archive_catalog: {
    title: '审计档案目录',
    exportFile: '审计档案目录.xls',
    autoFillFromProject: { projectName: 'name' },
    fields: [
      { key: 'projectName', label: '项目名称', fullSpan: true },
      { key: 'archiverName', label: '归档人' },
      { key: 'archiveDate', label: '归档日期', type: 'date' },
      { key: 'catalogContent', label: '档案目录内容', type: 'textarea', rows: 12, fullSpan: true, placeholder: '按顺序列出归档文件清单' },
      { key: 'totalPages', label: '总页数' },
      { key: 'totalFiles', label: '总件数' },
    ],
  },
};
